model asp.net_core/Controllers/Adm/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;

namespace model_asp.net_core.Controllers.Admin
{
    public class AuthenticationController : Controller
    {
        public IActionResult Index()
        {
            return View("Views/Admin/Authentication/Index.cshtml");
        }
    }
}

model asp.net_core/Controllers/Adm/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace model_asp.net_core.Controllers.Admin
{
    public class DashboardController : Controller
    {
        [Route("")]
        [Route("dashboard")]
        [Route("dashboard/index")]
        public IActionResult Index()
        {
            return View("Views/Adm/Dashboard/Index.cshtml");
        }
    }
}

model asp.net_core/Controllers/Adm/ServiceController.cs
using Microsoft.AspNetCore.Mvc;

namespace model_asp.net_core.Controllers.Admin
{
    public class ServiceController : Controller
    {
        public IActionResult Index()
        {
            return View("Views/Admin/Service/Index.cshtml");
        }
    }
}

model asp.net_core/Views/Shared/_AppLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/app.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
</head>
<body>
    <header>
        <section>
            <div class="logo">
                <a asp-area="" asp-controller="Home" asp-action="Index">
                    <label>
                        <i class="fa-solid fa-shield-halved"></i>
                    </label>
                </a>
            </div>
            <div>
                <div>
                    <i class="ri-search-line"></i>
                    <input type="text" placeholder="Pesquise ou digite um comando" />
                </div>
                <div>
                    <i class="fa-regular fa-bell"></i>
                </div>
                <div>
                    <label>
                        <img src="~/img/profile/user-32.png" alt="profile-image" />
                    </label>
                </div>
            </div>
        </section>
    </header>
    <main>
        <section class="sec">
            <div class="menu">
                <i class="ri-menu-line"></i>
                <h5>@ViewData["Menu"]/</h5>
                <h5> @ViewData["Translate"]</h5>
            </div>
            <div></div>
            <div class="state">
                <a>+</a>
                <a>
                    <i class="ri-calendar-line"></i>
                    Minha agenda
                </a>
            </div>
        </section>
        <section class="sec">
            <nav>
                <ul>
                    <li>
                        <a asp-area="" asp-controller="Dashboard" asp-action="Index">
                            <i class="ri-dashboard-line"></i>
                            Dashboard
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Employee" asp-action="Index">
                            <i class="ri-menu-add-line"></i>
                            Cadastro
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Ajaxi" asp-action="Index">
                            <i class="ri-barcode-box-line"></i>
                            Estoque
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Courses" asp-action="Index">
                            <i class="ri-shopping-bag-line"></i>
                            Vendas
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="ri-shopping-cart-line"></i>
                            Compras
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Contact" asp-action="Index">
                            <i class="ri-money-dollar-circle-line"></i>
                            Finânceiro
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Service" asp-action="Index">
                            <i class="ri-briefcase-line"></i>
                            Serviços
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Contact" asp-action="Index">
                            <i class="ri-account-circle-line"></i>
                            Recursos humanos
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Contact" asp-action="Index">
                            <i class="ri-file-chart-line"></i>
                            Relatórios
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Contact" asp-action="Index">
                            <i class="ri-question-line"></i>
                            Suporte
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Contact" asp-action="Index">
                            <i class="ri-tools-line"></i>
                            Utilitários
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Contact" asp-action="Index">
                            <i class="ri-settings-4-line"></i>
                            Configurações
                        </a>
                    </li>
                </ul>
            </nav>
            <div>
                @RenderBody()
            </div>
        </section>
    </main>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/chart.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11" asp-append-version="true"></script>
    <script src="~/js/appLayout.js" asp-append-version="true"></script>
</body>
</html>

model asp.net_core/Views/Shared/_SiteLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
</head>
<body>
    <header>
        <nav>
            <div class="logo">
                    <i class="fa-solid fa-shield-halved"></i>
                </div>
            <div>
                <!--<div class="logo">
                    <i class="fa-solid fa-shield-halved"></i>
                    <h1>Solus</h1>
                </div>-->
                <ul>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Soluções</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Funcionalidades</a></li>
                    <li><a asp-area="" asp-controller="Courses" asp-action="Index">Planos e Preços</a></li>
                    <li><a asp-area="" asp-controller="Contact" asp-action="Index">Seja um parceiro</a></li>
                    <li><a asp-area="" asp-controller="Contact" asp-action="Index">Sobre</a></li>
                </ul>
            </div>
            <ul>
                <li><a asp-area="" asp-controller="Authentication" asp-action="Index">
                        <i class="ri-user-line"></i>
                    Entrar</a></li>
                <li><a asp-area="" asp-controller="Authentication" asp-action="Index">Teste grátis</a></li>
            </ul>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        <div class="container">
            &copy;2023 Solus Inc. <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>